### ISSUE TITLE
support oneliner of `:CSV foo.csv` with tailing nGQL.

### ISSUE THREAD

**Issue by wey-gu** [vesoft-inc/nebula-console#141]
One of our users was trying to create some script to automate nGQL query to output result in CSV leveraging console `:CSV` syntax.

The current semantic of `:CSV` means to save the next line of `:CSV` result to file, which is clear and making a lot of sense :).

While in this user's need, the shell script is calling console `-e`, thus the only thing it could done are something like:
```
console ... -e `use foo; :csv bar.csv; go from ...`
```

This should not be supported for the initial definition of `:CSV` as it only means to output query in next line.

The way to support this was to alternatively use `-f filename` where in the file, multi-line of `use foo;\n:csv bar.csv;\n go ...` was placed.

But with this, I would like to ask for help on considering changing our semantic of `:CSV` on allowing its tailing query to output to the file if exists.

```
 :csv bar.csv; go from ...
```

Do you think this makes sense?

Thanks

**Comment by jievince** [comment]
> :csv bar.csv; go from ...
Do you think this makes sense?
This was considered when we first designed the `: CSV` syntax, but because Nebula’s server-side syntax allows multiple statements separated by semicolons, so putting a semicolon on the same line between a client statement and a server statement can create some confusing situations, such as:
```
$var=go from...; : csv a.csv; $var2=...;
```
